src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 500)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $picture_1 = null;

    #[ORM\Column(length: 255)]
    private ?string $picture_2 = null;

    #[ORM\Column(length: 255)]
    private ?string $picture_3 = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPicture1(): ?string
    {
        return $this->picture_1;
    }

    public function setPicture1(string $picture_1): static
    {
        $this->picture_1 = $picture_1;

        return $this;
    }

    public function getPicture2(): ?string
    {
        return $this->picture_2;
    }

    public function setPicture2(string $picture_2): static
    {
        $this->picture_2 = $picture_2;

        return $this;
    }

    public function getPicture3(): ?string
    {
        return $this->picture_3;
    }

    public function setPicture3(string $picture_3): static
    {
        $this->picture_3 = $picture_3;

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('picture_1',  FileType::class,[
                
                'label' => 'Image de couverture (image file)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => true,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '5000k',
                        'extensions' => [
                            'jpg','png','jpeg'
                        ],
                        'mimeTypesMessage' => 'Please upload a valid photo document',
                    ])
                    ],
                    'data_class' => null,
            ])


            ->add('picture_2',  FileType::class,[
                'label' => 'Deuxieme image (image file)',

                // unmapped means that this field is not associated to any entity property
                'mapped' => true,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '5000k',
                        'extensions' => [
                            'jpg','png','jpeg'
                        ],
                 
                        'mimeTypesMessage' => 'Please upload a valid photo document',
                    ])
                    
                    ],
                    'data_class' => null,
            ])
            ->add('picture_3',  FileType::class, [
                'label' => '3eme image (image file)',
                
                // unmapped means that this field is not associated to any entity property
                'mapped' => true,
                'required' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
             
                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '5000k',
                        'extensions' => [
                            'jpg','png','jpeg'
                        ],
                        'mimeTypesMessage' => 'Please upload a valid photo document',
                    ])
                    ],
                    'data_class' => null,
            ])
          
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\File\File;

#[Route('/article')]
class ArticleController extends AbstractController
{
    #[Route('/', name: 'app_article_index', methods: ['GET'])]
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', [
            'articles' => $articleRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_article_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger,): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $picture_1 = $form->get('picture_1')->getData();
            $picture_2 = $form->get('picture_2')->getData();
            $picture_3 = $form->get('picture_3')->getData();

            if ($picture_1) {
                $originalFilename = pathinfo($picture_1->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$picture_1->guessExtension();
                $article->setPicture1($newFilename);
                $entityManager->flush();
                // Move the file to the directory where brochures are stored
                try {
                    $picture_1->move(
                        $this->getParameter('photo_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $article->setPicture1($newFilename);
            }

               //TRAITEMENT PHOTO 2 //

               if ($picture_2) {
                $originalFilename = pathinfo($picture_1->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$picture_2->guessExtension();
                $article->setPicture2($newFilename);
                $entityManager->flush();
                // Move the file to the directory where brochures are stored
                try {
                    $picture_2->move(
                        $this->getParameter('photo_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $article->setPicture2($newFilename);
            }

             //TRAITEMENT PHOTO 3 //

             if ($picture_3) {
                $originalFilename = pathinfo($picture_1->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$picture_3->guessExtension();
                $article->setPicture3($newFilename);
                $entityManager->flush();
                // Move the file to the directory where brochures are stored
                try {
                    $picture_3->move(
                        $this->getParameter('photo_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $article->setPicture3($newFilename);
            }



            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }
/* CREATION VU EN SAVOIR PLUS COTE UTILISATEUR*/
    #[Route('/{id}', name: 'app_article_user_show', methods: ['GET'])]
    public function show_article_to_user(Article $article): Response
    {
        return $this->render('home/articleShow.html.twig', [
            'article' => $article,
        ]);
    }



    #[Route('/{id}', name: 'app_article_show', methods: ['GET'])]
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_article_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_article_delete', methods: ['POST'])]
    public function delete(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
      /*  if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($article);
            $entityManager->flush();
        }
*/
        
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager->remove($article);
            $todelete=$article->getPicture1();
            $entityManager->flush();

            if ($todelete ){
                $path=$this->getParameter("photo_directory").'/'.$todelete;
    
                // verifier que limage existe //
               
                        unlink($path);
                
            
            }
         ;
        }
        

        return $this->redirectToRoute('app_article_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('app_article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <h1>Edit Article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

<<<<<<< HEAD
   {% block stylesheets %}
     <link rel="stylesheet" {{ asset('assets/style/devNotes.css') }}> 

    {% endblock %}
=======
>>>>>>> 6048c15717de7050c491dea1b61beb01b674aa99
{% block title %}Article index{% endblock %}

{% block body %}

    {{ include('admin_navbar.html.twig') }}
<<<<<<< HEAD
   <div class="devNotice" >
   <p > Espace administrateur en cours de developpement </p> 
  </div>
      <!--- Image des article en cours 
                        <div class="articleContainer">
                        <div class="headerTitle">Actualiter en ligne </div>
                        {% for article in articles %}
                        <div class="a_items">
                            
                        
                                <h1>{{ article.title }}</h1>
                                <p>{{ article.description }}</p>
                                
                                <div class="picture">
                                    <img  src="{{ asset('uploads/photos/' ~ article.picture1) }}" alt="photo">
                                </div>
                                
                                <div class="picture">
                                    <img  src="{{ asset('uploads/photos/' ~ article.picture2) }}" alt="photo">
                                </div>
                                
                                <div class="picture">
                                    <img  src="{{ asset('uploads/photos/' ~ article.picture3) }}" alt="photo">
                                </div>
                        
                                    <a href="{{ path('app_article_show', {'id': article.id}) }}">Voir</a>
                                    <a href="{{ path('app_article_edit', {'id': article.id}) }}">Modifier</a>
                        
                        </div>
                        {% else %}
                            <tr>
                                <td colspan="7">Pas d'article enregistré</td>
                            </tr>
                        {% endfor %}
                

                    <a href="{{ path('app_article_new') }}">Ajouter un article</a>

-->


{% endblock %}
=======
   
   
        <div class="articleContainer">
        <div class="headerTitle">Actualiter en ligne </div>
        {% for article in articles %}
        <div class="a_items">
            
             
                <h1>{{ article.title }}</h1>
                <p>{{ article.description }}</p>
                
                <div class="picture">
                       <img  src="{{ asset('uploads/photos/' ~ article.picture1) }}" alt="photo">
                </div>
                
                <div class="picture">
                       <img  src="{{ asset('uploads/photos/' ~ article.picture2) }}" alt="photo">
                </div>
                
                <div class="picture">
                       <img  src="{{ asset('uploads/photos/' ~ article.picture3) }}" alt="photo">
                </div>
        
                    <a href="{{ path('app_article_show', {'id': article.id}) }}">Voir</a>
                    <a href="{{ path('app_article_edit', {'id': article.id}) }}">Modifier</a>
         
        </div>
        {% else %}
            <tr>
                <td colspan="7">Pas d'article enregistré</td>
            </tr>
        {% endfor %}
   

    <a href="{{ path('app_article_new') }}">Ajouter un article</a>
{% endblock %}
>>>>>>> 6048c15717de7050c491dea1b61beb01b674aa99

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <h1>Create new Article</h1>

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('app_article_index') }}">back to list</a>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
{{ include('navbar.html.twig') }}
  
   {% block stylesheets %}

    {% endblock %}
    <h1>Article</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ article.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ article.description }}</td>
            </tr>
            <tr>
                <th>Picture_1</th>
                <td>{{ article.picture1 }}</td>
            </tr>
            <tr>
                <th>Picture_2</th>
                <td>{{ article.picture2 }}</td>
            </tr>
            <tr>
                <th>Picture_3</th>
                <td>{{ article.picture3 }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_article_index') }}">back to list</a>

    <a href="{{ path('app_article_edit', {'id': article.id}) }}">edit</a>

    {{ include('article/_delete_form.html.twig') }}
{% endblock %}